controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_effort_controller:
      type: forward_command_controller/ForwardCommandController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    feedback_effort_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - joint_a
      - joint_b
      - joint_c
      - joint_d
      - joint_e
      - joint_f
    interface_name: position
    interface_name: velocity
    interface_name: effort

forward_effort_controller:
  ros__parameters:
    joints:
      - joint_a
      - joint_b
      - joint_c
      - joint_d
      - joint_e
      - joint_f
    interface_name: effort

forward_position_controller:
  ros__parameters:
    joints:
      - joint_a
      - joint_b
      - joint_c
      - joint_d
      - joint_e
      - joint_f
    interface_name: position

feedback_effort_controller:
  ros__parameters:
    joints:
      - joint_a
      - joint_b
      - joint_c
      - joint_d
      - joint_e
      - joint_f

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.001 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

    gains:
      joint_a:
        p: 1.0
        i: 0.0
        d: 1.0
        i_clamp: 1e+3

      joint_b:
        p: 1.0
        i: 0.0
        d: 1.0
        i_clamp: 1e+3

      joint_c:
        p: 1.0
        i: 0.0
        d: 1.0
        i_clamp: 1e+3

      joint_d:
        p: 1.0
        i: 0.0
        d: 1.0
        i_clamp: 1e+3

      joint_e:
        p: 1.0
        i: 0.0
        d: 1.0
        i_clamp: 1e+3

      joint_f:
        p: 1.0
        i: 0.0
        d: 1.0
        i_clamp: 1e+3